// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package git

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../git/templates", "-dot-gitignore.plush", "\"Ki5sb2cKLkRTX1N0b3JlCmRvYwp0bXAKcGtnCiouZ2VtCioucGlkCmNvdmVyYWdlCmNvdmVyYWdlLmRhdGEKYnVpbGQvKgoqLnBieHVzZXIKKi5tb2RlMXYzCi5zdm4KcHJvZmlsZQouY29uc29sZV9oaXN0b3J5Ci5zYXNzLWNhY2hlLyoKLnJha2VfdGFza3N+CioubG9nLmxjawpzb2xyLwouamh3LWNhY2hlLwpqaHcuKgoqLnN1YmxpbWUqCm5vZGVfbW9kdWxlcy8KZGlzdC8KZ2VuZXJhdGVkLwoudmVuZG9yLwpiaW4vKgpnaW4tYmluCi5pZGVhLwo=\"")
}
