// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package initgen

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../initgen/templates", "-dot-travis.yml", "\"bGFuZ3VhZ2U6IGdvCgpzdWRvOiBmYWxzZQoKZ286CiAgLSAxLjkueAogIC0gMS4xMC54CiAgLSAxLjExLngKICAtIHRpcAoKaW5zdGFsbDogbWFrZSBkZXBzCgpzY3JpcHQ6IG1ha2UgY2ktdGVzdAoKbWF0cml4OgogIGFsbG93X2ZhaWx1cmVzOgogICAgLSBnbzogJ3RpcCcKCg==\"")
}
