// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package goreleaser

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../goreleaser/templates", "-dot-goreleaser.yml.plush.tmpl", "\"YnVpbGRzOgotCiAgZ29vczoKICAgIC0gZGFyd2luCiAgICAtIGxpbnV4CiAgICAtIHdpbmRvd3MKICBlbnY6CiAgICAtIENHT19FTkFCTEVEPTAKICAjIG1haW46IHt7Lm9wdHMuTWFpbkZpbGV9fQoKY2hlY2tzdW06CiAgbmFtZV90ZW1wbGF0ZTogJ2NoZWNrc3Vtcy50eHQnCgpzbmFwc2hvdDoKICBuYW1lX3RlbXBsYXRlOiAie3sie3sifX0gLlRhZyB7eyJ9fSJ9fS1uZXh0IgoKY2hhbmdlbG9nOgogIHNvcnQ6IGFzYwogIGZpbHRlcnM6CiAgICBleGNsdWRlOgogICAgICAtICdeZG9jczonCiAgICAgIC0gJ150ZXN0OicKPCU9IGlmIChicmV3KSB7ICU+CmJyZXc6CiAgZ2l0aHViOgogICAgb3duZXI6IHt7IC5vcHRzLkJyZXdPd25lciB9fQogICAgbmFtZToge3sgLm9wdHMuQnJld1RhcCB9fQo8JSB9ICU+Cg==\"")
}
