// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package goreleaser

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../goreleaser/templates", "-dot-goreleaser.yml.plush", "\"YnVpbGRzOgotCiAgZ29vczoKICAgIC0gZGFyd2luCiAgICAtIGxpbnV4CiAgICAtIHdpbmRvd3MKICBlbnY6CiAgICAtIENHT19FTkFCTEVEPTAKICAjIG1haW46IDwlPSBvcHRzLk1haW5GaWxlICU+CiAgIyBiaW5hcnk6IHt7LkJpbmFyeX19CiAgIyBob29rczoKICAjICAgcHJlOiBwYWNrcgogICMgICBwb3N0OiBwYWNrciBjbGVhbgoKY2hlY2tzdW06CiAgbmFtZV90ZW1wbGF0ZTogJ2NoZWNrc3Vtcy50eHQnCnNuYXBzaG90OgogIG5hbWVfdGVtcGxhdGU6ICJ7eyAuVGFnIH19LW5leHQiCmNoYW5nZWxvZzoKICBzb3J0OiBhc2MKICBmaWx0ZXJzOgogICAgZXhjbHVkZToKICAgIC0gJ15kb2NzOicKICAgIC0gJ150ZXN0OicKYnJldzoKICBnaXRodWI6CiAgICBvd25lcjogPCU9IG9wdHMuQnJld093bmVyICU+CiAgICBuYW1lOiA8JT0gb3B0cy5CcmV3VGFwICU+Cg==\"")
}
