// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package goreleaser

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../goreleaser/templates", "-dot-goreleaser.yml.plush.tmpl", "\"YnVpbGRzOgotCiAgZ29vczoKICAgIC0gZGFyd2luCiAgICAtIGxpbnV4CiAgICAtIHdpbmRvd3MKICBlbnY6CiAgICAtIENHT19FTkFCTEVEPTAKICBtYWluOiB7ey5vcHRzLk1haW5GaWxlfX0KCmNoZWNrc3VtOgogIG5hbWVfdGVtcGxhdGU6ICdjaGVja3N1bXMudHh0JwoKc25hcHNob3Q6CiAgbmFtZV90ZW1wbGF0ZTogInt7Int7In19IC5UYWcge3sifX0ifX0tbmV4dCIKCmNoYW5nZWxvZzoKICBzb3J0OiBhc2MKICBmaWx0ZXJzOgogICAgZXhjbHVkZToKICAgICAgLSAnXmRvY3M6JwogICAgICAtICdedGVzdDonCjwlPSBpZiAoYnJldykgeyAlPgpicmV3OgogIGdpdGh1YjoKICAgIG93bmVyOiB7eyAub3B0cy5CcmV3T3duZXIgfX0KICAgIG5hbWU6IHt7IC5vcHRzLkJyZXdUYXAgfX0KPCUgfSAlPgo=\"")
}
